[package]
edition = "2024"
name = "loader"
version = "0.1.0"

[dependencies]
anyhow = "1.0.98"
clap = {version = "4.5.38", features = ["derive"]}
env_logger = "0.11.8"
indicatif = "0.17.11"
log = "0.4.27"
tokio = {version = "1.45.0", features = ["full"]}
tokio-serial = "5.4.5"
xmas-elf = "0.10.0"
