[package]
name = "arch"
version = "0.1.0"
edition.workspace = true

[lib]
name = "arch"
path = "src/lib.rs"
test = false
bench = false

[dependencies]
spin = "0.10.0"
qemu-exit = "3.0"
log = "0.4.27"

[target.'cfg(target_arch = "aarch64")'.dependencies]
arm_pl011 = "0.1"
