cargo-features = ["per-package-target"]

[package]
edition = "2024"
forced-target = "x86_64-unknown-linux-gnu"
name = "xtask"
version = "0.1.0"

[dependencies]
anyhow = "*"
clap = {version = "4.5", features = ["derive"]}
env_logger = "*"
log = "*"
num_cpus = "1.16.0"
xshell = "*"
