cargo-features = ["per-package-target"]

[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
forced-target = "x86_64-unknown-linux-gnu"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
