
[package]
edition = "2024"
name = "builder"
version = "0.1.0"

[dependencies]
anyhow = "1.0.98"
clap = {version = "4.5", features = ["derive"]}
env_logger = "0.11.8"
log = {version = "0.4.27"}
num_cpus = "1.16.0"
xshell = "0.2.7"
